project:
  type: website
  output-dir: docs

website:
  title: "PUFF SEMS forberedelse"
  navbar:
    left:
      - text: "PUFF SEMS forberedelse"
        href: slides/intro.qmd 
      - text: "normalfordelingen"
        href: slides/normalfordelingen.html




