project:
  type: website
  output-dir: docs

website:
  title: "KUB Datalab slides"
  navbar:
    left:
      - text: "normalfordelingen"
        href: slides/test20260115.qmd
        target: _blank




